### PR TITLE
fix(zigbee2mqtt-edge/config.json): Add missing support for adapter zs…

### LINKED ISSUE #336: Cannot enable option adapter: deconz
Currently, it is not possible to add the entry 

adapter: deconz 

in the configuration file in order to enable raspbee/conbee support for z2m on hassio. Adding the entry simply has no effect, and it also doesn't appear in the configuration file

### PR DESCRIPTION
**Pull request by LennardWesterveld**
Added the support of the serial.adapter thas was missing in the config validation. 

Fixes #336

### CODE REVIEW

**Comment by LennardWesterveld** [comment]
Why is this failing @danielwelch? and when can this be merged?

**Comment by the-hydra** [comment]
Any updates on when we can expect this PR to be merged @danielwelch ?

Thanks

**Comment by Twanislas** [comment]
Ping @danielwelch :)
This would fix #315 #336 #356 ... I'm pretty sure a bunch of people would be very happy ;)
Thanks !

**Comment by Twanislas** [comment]
Thank you Daniel !

**Pull request merged**
