### PR TITLE
Update more settings 

### PR DESCRIPTION
**Pull request by dzungpv**
@danielwelch I update more settings here: http://www.zigbee2mqtt.io/configuration/configuration.html

### CODE REVIEW

**Comment by dzungpv** [comment]
I add it here https://github.com/danielwelch/hassio-zigbee2mqtt/pull/185, please waiting for update

**Comment by danielwelch** [comment]
Thanks for doing this. My concern here for ban, whitelist, queue, etc. is that hassio will require the entry of empty lists (like the network_key saga) rather than allow the user to omit the list entirely. Last I checked, there was no schema syntax for allowing lists to be optional, just the items within the list. This may have changed, so let me know if it has.

If that's the case, 2 problems:
1. We need to at least add corresponding empty lists to config.json[options], so that the default configuration will start without throwing an error
2. I'm worried that passing an empty whitelist will be treated as just that, and no devices will be allowed to join. I have not dug into the zigbee2mqtt source code to see how this situation would be handled.

Have you tested these changes locally?

**Comment by dzungpv** [comment]
@danielwelch I am not test it locally, but without all the configuration, user could not user all the features, because you remove **override** option, so every time i change in the file, it revert back to original and there is noway to use it, not like previous version.
All those are optional, user see error with network key because you include that in default options :
```
  "options": {
    "data_path": "/share/zigbee2mqtt",
    "devices": "devices.yaml",
    "groups": "groups.yaml",
    "homeassistant": true,
    "permit_join": false,
    "mqtt": {
      "base_topic": "zigbee2mqtt",
      "server": "mqtt://homeassistant",
      "user": "my_user",
      "password": "my_password"
    },
    "serial": {
      "port": "/dev/ttyACM0"
    },
    "advanced": {
      "pan_id": 6754,
      "channel": 11,
      "network_key": []
    }
  }
```
If all the config i has added not in default one, no error will occurs.

With my update from 1.4.1, it merge old configuration with default one, that cause the issue.
So for the breaking update you remove : **"network_key": []**, tell user press "RESET TO DEFAULT" and then fill from the old configuration file and it will work, like some user here: https://github.com/danielwelch/hassio-zigbee2mqtt/issues/183#issuecomment-513538899

**Comment by dzungpv** [comment]
@danielwelch I tested by remove the network key, there are error, so we need test more

**Comment by danielwelch** [comment]
Yeah, we’ve run into this problem in testing historically. It’s the reason network_key is in the defaults. It’s a limitation of hassio unfortunately. At the very least, we can go ahead and merge in the non-nested options here?

**Comment by dzungpv** [comment]
@danielwelch this error when empty network key array:
```
/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/controller.js:429
                    throw new TypeError('net.precfgkey should be an array with 16 uint8 integers.');
                    ^
TypeError: net.precfgkey should be an array with 16 uint8 integers.
    at /zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/controller.js:429:27
    at Object._.forOwn (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/node_modules/busyman/index.js:242:27)
    at Object._.forEach (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/node_modules/busyman/index.js:415:18)
    at Controller.setNvParams (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/components/controller.js:414:7)
    at new ZShepherd (/zigbee2mqtt-1.5.1/node_modules/zigbee-herdsman/dist/lib/shepherd.js:28:21)
    at Zigbee.start (/zigbee2mqtt-1.5.1/lib/zigbee.js:57:25)
    at startupLogVersion (/zigbee2mqtt-1.5.1/lib/controller.js:167:25)
    at utils.getZigbee2mqttVersion (/zigbee2mqtt-1.5.1/lib/controller.js:193:13)
    at git.getLastCommit (/zigbee2mqtt-1.5.1/lib/util/utils.js:102:9)
    at /zigbee2mqtt-1.5.1/node_modules/git-last-commit/source/index.js:44:5
```
So it is require not an optional right @Koenkk ?

**Comment by dzungpv** [comment]
@danielwelch I think it is safe with not require one, check here: https://github.com/Koenkk/zigbee-herdsman/blob/4485b8f8de23df81173b35e17b1d5c0fc9ccaf6a/src/lib/components/controller.ts#L507 just some are required, one is network key

**Comment by dzungpv** [comment]
@danielwelch just add default network key use by z2m to your and it will work like before: https://github.com/Koenkk/zigbee2mqtt/blob/ac3b924065c6f2b9dd7433a6f193d1924b34bb7d/lib/util/settings.js#L88

**Comment by dzungpv** [comment]
@danielwelch About 2:
"I'm worried that passing an empty whitelist will be treated as just that, and no devices will be allowed to join. I have not dug into the zigbee2mqtt source code to see how this situation would be handled."
Empty whitelist do nothing, i am author of whitelist feature: https://github.com/Koenkk/zigbee2mqtt/pull/1654 and the same for ban option, so i think it is safe with this PR. I have not any docker environment to test local.

**Comment by danielwelch** [comment]
> i am author of whitelist feature
well, that's pretty convincing 😆 I'm ok with merging this for the edge branch only, and you can test it out.

**Comment by dzungpv** [comment]
@danielwelch I don't understand what you mean, you tel me just change for the https://github.com/danielwelch/hassio-zigbee2mqtt/blob/master/zigbee2mqtt-edge/config.json right?

**Comment by dzungpv** [comment]
@danielwelch when new build image available?

**Comment by dzungpv** [comment]
@danielwelch I confirm it work, but must add empty array for those option: ban, whitelist,availability_blacklist, and  queue must set default value, so minimum default config must:
```
{
  "data_path": "/share/zigbee2mqtt",
  "devices": "devices.yaml",
  "groups": "groups.yaml",
  "homeassistant": true,
  "permit_join": false,
  "mqtt": {
    "base_topic": "zigbee2mqtt",
    "server": "mqtt://homeassistant",
    "user": "my_user",
    "password": "my_password"
  },
  "serial": {
    "port": "/dev/ttyACM0"
  },
  "ban": [],
  "whitelist": [],
  "advanced": {
    "pan_id": 6754,
    "channel": 11,
    "network_key": [must set],
    "availability_blacklist": [],
  },
  "queue": {
    "delay": 250,
    "simultaneously": 5
  }
}
```

So just another breaking change, but i thing we must do it because default z2m must have those empty array https://github.com/Koenkk/zigbee2mqtt/blob/ac3b924065c6f2b9dd7433a6f193d1924b34bb7d/lib/util/settings.js#L8

**Comment by danielwelch** [comment]
That’s ok, we can add the blank lists and default queue settings to config.json[options]

**Comment by dzungpv** [comment]
@danielwelch It is OK, i have new PR here: https://github.com/danielwelch/hassio-zigbee2mqtt/pull/195

**Comment by danielwelch** [comment]
closed in favor of #195

**Pull request closed without merging**
