### PR TITLE
v1.5.1 and restructured configuration

### PR DESCRIPTION
**Pull request by danielwelch**
### TODO:

- [x] upgrade version to 1.5.0 (config.json, dockerfile)
- [x] fix `pan_id` issue https://github.com/danielwelch/hassio-zigbee2mqtt/issues/150
- [ ] add `ext_pan_id`? (see above issue)
- [x] replace edge slug: `zigbee2mqtt_edge`
- [x] map in config folder https://github.com/danielwelch/hassio-zigbee2mqtt/issues/119
- [x] fix commit hash unknown issue: https://github.com/danielwelch/hassio-zigbee2mqtt/issues/146, https://github.com/Koenkk/zigbee2mqtt/blob/master/docker/Dockerfile.arm64v8, https://stackoverflow.com/questions/45469133/create-json-file-using-jq
- [x] documentation updates
- [ ] reconcile any new 1.5 options

This pull request restructures how the add-on configuration is set. **It contains breaking changes** that will require changing your add-on configuration in the Hass.io UI to conform to the new schema.

### Breaking Changes
- Many of the configuration options will be changed. See the associated `zigbee2mqtt-edge/config.json` schema for the new config option names until these changes are documented when they land in stable.
- Devices and Groups should now be defined in separate files, which are saved in your `$DATA_PATH`. The file names are configurable via the `devices` and `groups` options (ex: `"devices": "devices.yaml"`). This is necessary as the depth of nesting required for some zigbee2mqtt options isn't possible with Hass.io add-on configuration, which limits nesting of config options.

### Improvements
- Simplifies configuration structure: just write zigbee2mqtt configuration formatted in the same way it is presented in the zigbee2mqtt docs, but in JSON rather than YAML.
- Removes the python 3 dependency altogether, reducing image size and and hopefully dealing with bugs related to python3, Docker, and 64-bit systems/images.

### Back up existing configurations
Because of the breaking changes, and because we don't want anyone to lose their network key and have to repair their whole network (thanks @deisi), any existing `configuration.yaml` will be saved to `$DATA_PATH/.configuration.yaml.bk` when the add-on is started.

### CODE REVIEW

**Comment by danielwelch** [comment]
@deisi the new 1.4 release of zigbee2mqtt seems like a good time to land this in stable. I’ll ping @Koenkk for his thoughts as well, as it’s a big change. This would take care of a lot of issues.

**Comment by Koenkk** [comment]
This indeed looks like a logical change.

I'm wondering how existing users will migrate, do they need to configure from scratch?

**Comment by deisi** [comment]
I think one needs to configure from scratch. Mostly we were worried by deleting the key and thus danielwelch added  a a mechanism for creating a backup of the old file. That way we at least don't delete valuable data. There would still be the possibility of going the same route as the [appdaemon](https://github.com/hassio-addons/addon-appdaemon) people. They just made a new repository and called it version 2.  That way it was clear people had to migrate them self.

**Comment by Koenkk** [comment]
That might actually be a good idea, things shouldn't break when users just press the 'update' button.

**Comment by dzungpv** [comment]
Most use off HA and Z2m are advance use, they must deal with many breaking change from HA also.
The z2m project change much from the beginning, so i think just warning the breaking is enough.  
Time care about good features and stability make the project better

**Comment by Koenkk** [comment]
Is such a warning possible?

**Comment by danielwelch** [comment]
As another user suggested in a different thread: in addition to the typical changelog, we could add a Readme that displays in the Hassio UI with the breaking change warning. The Hassio dev docs don’t actually document how to do this, but inferring from the community add-ons, it seems like just including a readme file at the add-on level does the trick.

**Comment by danielwelch** [comment]
My proposal: I'll release 1.4, keeping things largely the same, with a new README that warns of the breaking change to come in 1.5. Then I'll merge this before 1.5 and the breaking changes will be in effect then. How does that sound @Koenkk ? If that's ok, would you mind pinging me when version 1.5 is getting close?

**Comment by Koenkk** [comment]
Sounds like a good idea! Will let you know once 1.5 is around the corner.

**Comment by james-fry** [comment]
> As another user suggested in a different thread: in addition to the typical changelog, we could add a Readme that displays in the Hassio UI with the breaking change warning. The Hassio dev docs don’t actually document how to do this, but inferring from the community add-ons, it seems like just including a readme file at the add-on level does the trick.

I saw you did what I suggested and it works great!

**Comment by JustinHoeky** [comment]
Can someone tell me the status on this topic?
Planning on migrating to HA, but waiting for this version before migrating all my devices (because of the "Breaking Changes Notice")

**Comment by deisi** [comment]
@JustinHoeky 
Well you could use the version from github with the patches inside. Also the breaking change is not that bad. It just concerns your setup, not the zigbee network, so you don't have to repair everything. Its mostly about adjusting your config.

**Comment by TheZoker** [comment]
@danielwelch Version 1.5.0 of zigbee2mqtt was released yesterday. Maybe you can upgrade the version with this PR as well

**Comment by timkent** [comment]
Hi @danielwelch, I notice `ext_pan_id` configuration support was on the TODO list above, will it be added in the future?

Cheers!

**Pull request merged**
