### PR TITLE
Add support of experimental transmit_power feature to zigbee2mqtt stable.

### PR DESCRIPTION
**Pull request by dmitrybabeshko**
See https://github.com/Koenkk/zigbee2mqtt/issues/2253

### CODE REVIEW

**Comment by dmitrybabeshko** [comment]
@danielwelch Any chance to get this pushed?
Thank you in advance!

**Comment by nanobra1n** [comment]
@danielwelch Is there any particular reason not to merge this? I know this settings is marked as experimental, but it can be useful to the stable user.

**Comment by lesleypersyn** [comment]
I get this warning now in the system log hass.io and the non-edge is not displayed anymore in the add-ons.
_20-05-23 11:42:10 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt/config.json: does not match regular expression for dictionary value @ data['schema']['experimental']['transmit_power']. Got 'int(-22,19)?'_

**Comment by danielwelch** [comment]
@dmitrybabeshko Unfortunately, this ended up breaking the add-on and I rolled it back. I’ll have to look into what the problem was, but hopefully can continue to work on this.

**Comment by dmitrybabeshko** [comment]
@danielwelch Sorry for this breaking change. Please check the corrected pull request https://github.com/danielwelch/hassio-zigbee2mqtt/pull/342.

**Pull request merged**
