### PR TITLE
Make use of nested configuration **Breaking Change** 

### PR DESCRIPTION
**Pull request by deisi**
- See 82f7b41 for most of the documentation
- Config is parsed as json and not yaml. Because json is a subclass of yaml and
  z2m excepts yaml this works well
- makes use of [device and group config](https://github.com/Koenkk/zigbee2mqtt.io/blob/dev/configuration/configuration.md#specifying-devices-and-groups-in-a-separate-file) as it was added to z2m with https://github.com/Koenkk/zigbee2mqtt/commit/516bd704c67b0c86a323e5d90d9149d539fa6e7e
  this splits off group and device config from the main config, as it is not trivial to manage user input
  and z2m independently manipulating a common config file.

### CODE REVIEW

**Comment by danielwelch** [comment]
Nice. The splitting off of devices and groups is a great change as it saves us from the Hassio limitations related to nesting. I’m assuming that zigbee2mqtt looks for those files in the same directory as configuration.yaml? Don’t think this behavior is documented. I’ll also think about how we can test this prior to deploying moving forward.

**Comment by deisi** [comment]
>  I’m assuming that zigbee2mqtt looks for those files in the same directory as configuration.yaml?

Yes, on my testing setup it works this way

>  Don’t think this behavior is documented.

you mean that it looks for it in the same file as `configuration.yaml`? Yes this is not documented. The rest is at https://github.com/Koenkk/zigbee2mqtt.io/blob/dev/configuration/configuration.md#specifying-devices-and-groups-in-a-separate-file

>  I’ll also think about how we can test this prior to deploying moving forward.

Year I'd like to hear how we could go on, not breaking to may setups. In particular I'm worried about `network_key`, I fear we might overwrite it for some people at some point and they don't have it backed up somewhere. Forcing them to repair all there devices. Hell I would be pissed if this happens.

Maybe we should setup a way of making a backup of the current config by copying to a sub folder of `data_path`. Once the backup is completed, we make a file called `.made_backup`. On subsequent runs, we check if the file `.made_backup` exists and skip the backup creation.

Or even further, instead of backing up, we initially merge the configurations once. This way we hopefully not mess up all the configs out there. However we would need to write some sort of parser just for this purpose.

**Comment by danielwelch** [comment]
@deisi Why the decision to build the edge version locally?

I'm thinking I'll merge this into a new `dev` branch for testing on my local machine. Maybe the `dev` branch can also have some "extras" in it that we have discussed on a previous issue that make it easier to develop, test, and build images locally.

**Comment by deisi** [comment]
> Why the decision to build the edge version locally?
I don't know how else can test this on my server. I thought once we have tested it, we add the `image` again.

> `dev` branch sound like a good idea. However if `dev` is so fundamentally different then master, simply merging `dev` into `master` for updates will not work. You have do to some sort of cherry picking and maybe do it by hand.

**Comment by deisi** [comment]
should I make this pr against the dev branch now?

**Comment by danielwelch** [comment]
Thanks, I tested this locally and things build and run. I'm going to work on the run script a little as well before merging anything into `master` and, therefore, updating the published edge version. I think you're right that it'd be a good idea to preserve former `configuration.yaml` files, particularly for the purposes of `network_key`. It'd be possible to merge with old config with jq, but the desired behavior for a first run would be to merge but keep the "old" stuff from `configuration.yaml`, while on subsequent runs the desired behavior would be the opposite (override old config with updated options from front-end). Therefore, I think the back-up solution is the simplest for our specific need right now. I could be missing something though, so let me know.

I'm also going to write up a `CONTRIBUTING.md` with some basic instructions for setting up for local development of this add-on.

**Pull request merged**
