### PR TITLE
adding back in configuration via UI

### PR DESCRIPTION
**Pull request by danielwelch**

### CODE REVIEW

**Comment by danielwelch** [comment]
@ciotlosm This pull request should add back in the UI configuration we want. It exists along side the data_path option in the Hass.io UI, which also needs to be configured. Some other differences from last time:
- The `set_config.py` script actually checks for an existing `configuration.yaml` within the data path. If it finds one, it will load it and overwrite the fields set in the UI. This way, we don't lose anything that's persisted in that file, like pretty names. If it doesn't find one, it creates one at `$DATA_PATH/configuration.yaml`.
- Behind the scenes, I'm just passing `/data/options.json` to the python script and having Python do the parsing, rather than parsing each option individually and passing them into a many-argumented script call.

**Comment by ciotlosm** [comment]
@danielwelch looks really good

**Comment by ciotlosm** [comment]
How soon will this get into master? Looking forward for some testing

**Comment by danielwelch** [comment]
Sorry, forgot to resolve the README merge conflict here. Happy testing, let me know how it goes!

**Comment by ciotlosm** [comment]
So far I think I took one step back, as I switched from RPI1 to OPI PC2 and now using aarch64 something is not happy at container start, but I will keep digging. Once I get some results I'll report back.

**Pull request merged**
