### PR TITLE
add external_converters option and support more options

### PR DESCRIPTION
**Pull request by lovelylain**

### CODE REVIEW

**Comment by nurikk** [comment]
Bump

**Comment by IronButterfly** [comment]
Please fix it ASAP!

**Comment by klim123123** [comment]
Please fix. New version released today. Still not fixed.

**Comment by nurikk** [comment]
Any updates on this?

**Comment by andreypolyak** [comment]
Hey, can anyone merge it, please?
Thanks

**Comment by andriej** [comment]
@danielwelch ?

**Pull request merged**
