### PR TITLE
Bump version to 1.16.2

### PR DESCRIPTION
**Pull request by rstein**
#### Checklist

- [x] Change the version number in `zigbee2mqtt/Dockerfile`: `ENV ZIGBEE2MQTT_VERSION="$NEW_VERSION"`
- [x] Change the version number in `zigbee2mqtt/config.json`: `"version": "$NEW_VERSION"`
- [x] Add any new configuration options to `zigbee2mqtt/config.json` and `zigbee2mqtt-edge/config.json`.
- [x] Update the changelog, including any breaking changes, changes to underlying libraries, or new configuration options

### CODE REVIEW

**Comment by rstein** [comment]
Missed some config options, will update soon

**Comment by rstein** [comment]
It is now possible to define a list of files for the `devices` and `groups` options. Since this would be a change of the data type I am not quite sure how this can be changed here :) 

https://github.com/Koenkk/zigbee2mqtt/issues/2970

**Comment by rstein** [comment]
The `devices` and `groups` options should now allow for one or multiple files to be specified without breaking compatibility with existing configurations

**Comment by ciotlosm** [comment]
Looks good. Will merge today. 
@rstein any chance to make a similar PR against: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt as well?

**Comment by rstein** [comment]
@ciotlosm Sure, I am happy to. It seems I am unable to fork https://github.com/zigbee2mqtt/hassio-zigbee2mqtt without deleting my fork of this repository, so I will do that as soon as this PR is done.

**Comment by boesing** [comment]
@ciotlosm is this repository abandoned in favor of zigbee2mqtt/hassio-zigbee2mqtt?

**Comment by ciotlosm** [comment]
@boesing Not at the moment, no. We're keeping them in sync for now from a Z2M version perspective. The repository in the new org zigbee2mqtt/hassio-zigbee2mqtt will probably become the default one in the future. It does have a few benefits:
- faster pipelines
- better release process
- better logging
- better service management in the container (for socat)
- mqtt auto discovery

I think we will keep this repo as well just for the config reference for "previous" version, but we will see. When all side processes (like trigger dev & co) are completed on the new repo, I will prepare a MR in z2m docs to reflect all these changes.

**Comment by 2vpetrov** [comment]
You need to add default value for "host" parameter, because the new installation addon is crash.
20-12-02 19:37:23 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'
20-12-02 19:37:23 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt-edge/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'
20-12-02 19:37:23 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'
20-12-02 19:37:23 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/7ad98f9c/zigbee2mqtt-edge/config.json: does not match regular expression for dictionary value @ data['schema']['frontend']['host']. Got 'string?'

**Comment by ciotlosm** [comment]
@2vpetrov you can use https://github.com/zigbee2mqtt/hassio-zigbee2mqtt for now until a fix is released.

**Comment by rstein** [comment]
Argh sorry, I did not see that warning with the local addon installation :/

**Comment by boesing** [comment]
@ciotlosm So there is no downside when using the "official" "unofficial" repository under the zigbee2mqtt org?

**Comment by ciotlosm** [comment]
@boesing At the moment the only downside would be slightly different timeline to get both on same z2m version. Currently zigbee2mqtt org version didn't get upgraded especially after uncovering the current bug. 

Also there were some quirks to the new z2m org add-on because of the big refactoring. For example people using their own mqtt had issues after they tested the one with auto-discovery. That's why I recommend to people to test early if they can to iron out any problems before we switch to that as main repo.

**Pull request merged**
