### PR TITLE
Add support of experimental transmit_power feature to zigbee2mqtt-edge

### PR DESCRIPTION
**Pull request by dmitrybabeshko**
See https://github.com/Koenkk/zigbee2mqtt/issues/2253

### CODE REVIEW

**Comment by dmitrybabeshko** [comment]
@danielwelch 
Hello, Could you please merge this change?

**Comment by danielwelch** [comment]
Can you add an empty experimental section to the options section as well? So the default configuration complies with the schema.

**Comment by dmitrybabeshko** [comment]
@danielwelch 
An empty experimental section has been added to the options section.

**Comment by CodeFinder2** [comment]
I would also be interessted in this feature! I think it should/can also be part in the stable release of the addon because it's itself marked as "experimental", isn't it? :see_no_evil:

**Pull request merged**
