### PR TITLE
Allow configuration of extended PAN ID for Release & Edge

### PR DESCRIPTION
**Pull request by felixstorm**
Similar to https://github.com/danielwelch/hassio-zigbee2mqtt/pull/250, but also for Non-Edge.

### CODE REVIEW

**Comment by felixstorm** [comment]
@Koenkk Do you have any further suggestions or should I change anything here? The missing extended PAN ID is currently the only reason why I cannot use the official zigbee2mqtt addon.

In case you would prefer to extend and merge #250 and just close this one, that would be completely fine for me as well. I only added this pull request since there had been no activity on #250 for some time...

Thanks,
Felix

**Comment by danielwelch** [comment]
Thanks Felix. Is it a viable alternative to set the default to an empty list? I’d prefer that, but I’m not sure how zigbee2mqtt would handle this (ignore it, use default, or error). 

Unfortunately this will be a breaking change in that configs will need to be updated for existing users to include ext_pan_id.

**Comment by felixstorm** [comment]
@danielwelch - sorry for not even considering that this could be a breaking change (after Koen had asked for it to be implemented also for non-edge in #250).

Looking through the code and testing a bit, I found the following aspects:
* zigbee2mqtt itself uses a default of `[0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD, 0xDD]` internally. When I do not specify `ext_pan_id` in `configuration.yaml`, I can still see it being used in my (debug-)log: `zigbee2mqtt:debug 2019-12-05T11:00:34: Zigbee network parameters: {"panID":6754,"extendedPanID":"0xdddddddddddddddd","channel":11}`
* Setting an empty list unfortunately does not seem to work (`ext_pan_id: []` will end up in the debug log as `"extendedPanID":"0x00000a4b00000004"`).

So my conclusion would be:
* Technically we could probably use a default of `"ext_pan_id": [221, 221, 221, 221, 221, 221, 221, 221]` since the same will be used internally anyway if nothing is set, but users would potentially need to add it to their configuration manually when updating. Another - IMHO major - downside would be that if everyone then has the default literally inside his/her config, it would become nearly impossible to change the default later.
* Therefore I would feel a lot better if we could make the whole property optional in the HA add-on schema. Do you know if something like ` "ext_pan_id": [ "int(0,255)?" ]?` (with a question mark behind the closing bracket) would be possible in the schema definition?

Thanks,  
Felix

**Comment by danielwelch** [comment]
> Do you know if something like "ext_pan_id": [ "int(0,255)?" ]? (with a question mark behind the closing bracket) would be possible in the schema definition?

As far as I know, this isn't possible (I know in the past it wasn't possible, as we've run into this problem with all of our "optional nested" configuration).

**Comment by magpern** [comment]
Can this somehow be included soon?
I have a bunch of livolo devices that I want to use, and what I understand, they require a ex_pan_id different from default.

Alternatively, Is there a way to compile a docker image on my own with this commit? (how? I have some knowledge of compiling self-made containers)

**Comment by felixstorm** [comment]
@magpern The road blocker currently is that we would like to make the extended pan ID optional to not break existing installations - which seemingly will need changes to either Home Assistant (preferred, to allow for optional nested configs) or zigbee2mqtt (inferior solution, treat empty extended pan id as not provided).  
And unfortunately I am out of town currently and also my time is a bit limited for now, so it will be at least a week or two until I will be able to take a look at this again. And then a potential PR to HA (although my Python knowledge is quite limited) would probably take another few weeks until the change would appear in a HA release version.

In the meantime, you could probably fork this repo yourself and cherry pick this commit if you need it sooner. As it‘s only the HA add-on configuration schema that needs to be changed, there is no need for a change in the docker image. You just need to add your changed fork of the repo as an additional add-on repository to your Hass.io (under „Add-On Store“) and then install the add-on from there.

**Comment by felixstorm** [comment]
@danielwelch Although being able to generally make "nested" config optional for any HA add-on would probably be the better solution, implementing a solid PR for this would likely be quite difficult for me (very limited Python knowledge, no viable test system for hassio-supervisor etc.).

Seeing that https://github.com/danielwelch/hassio-zigbee2mqtt/issues/259 and https://github.com/home-assistant/hassio-supervisor/pull/1391 have also not yet been resolved, the idea came to my mind to optionally allow for `network_key_string` and `support_ext_pan_id_string` in addition to the regular fields. Users could provide both values as hex strings (`str?`, should also allow for usage of `!secret`) and `run.sh` could then convert them back to the required format and field. I will see if I can come up with some `jq` magic for this and post it here in case of success.

Another option (although it would not solve https://github.com/danielwelch/hassio-zigbee2mqtt/issues/259) would be to just have `run.sh` remove `support_ext_pan_id` using `jq` if it's an empty list - that would allow us to at least set the default to an empty list (as you suggested here https://github.com/danielwelch/hassio-zigbee2mqtt/pull/263#issuecomment-561850043).

**Comment by felixstorm** [comment]
> Users could provide both values as hex strings

Ok, conversion from hex to decimal does not seem to be supported by `jq` internally, but users could provide a comma-separated list of decimal values as a string. Just as they would do currently, but enclosed in quotes instead of brackets, e.g. `"221, 221, 221, 221, 221, 221, 221, 221"`. It should be possible to convert this notation back to an array of numbers relatively easy with `jq` - will see what I can come up with...

**Comment by felixstorm** [comment]
Closing in favor of #283 ("Support extended PAN ID (optional) & secret network_key").

**Pull request closed without merging**
