### PR TITLE
New configuration option advanced/adapter_delay and adapter: zigate, fixes #499, #498

### LINKED ISSUE #499: adapter_delay option missing
**zigbee2mqtt add-on version (if edge, please report commit hash):** 0.16.2

**Operating environment (HassOS, Virtual Machine, Device/platform running Home Assistant):** HA Supervised Debian 10

**Description of problem:**
Please add support of `adapter_delay` so it can be passed through to z2m as in Conbee thread: https://github.com/Koenkk/zigbee-herdsman/issues/72#issuecomment-748683612

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```json
advanced:
  adapter_delay: 
(should work)
```

**Your logs from Home Assistant**
`20-12-20 23:01:22 WARNING (MainThread) [supervisor.addons.validate] Unknown options adapter_delay`

### PR DESCRIPTION
**Pull request by kind3r**
#### Checklist

- [x] Change the version number in `zigbee2mqtt/config.json`: `"version": "$NEW_VERSION"`
- [x] Add any new configuration options to `zigbee2mqtt/config.json` and `zigbee2mqtt-edge/config.json`.
- [x] Update the changelog, including any breaking changes, changes to underlying libraries, or new configuration options

### CODE REVIEW

**Comment by ciotlosm** [comment]
Thanks for the PR. I will get to this tomorrow. It will have to get updated for 1.7.0

**Comment by ciotlosm** [comment]
I've taken your changes and applied them to https://github.com/zigbee2mqtt/hassio-zigbee2mqtt in 1.17.0

**Comment by kind3r** [comment]
Ok, then can I close this PR ?

**Comment by ciotlosm** [comment]
@kind3r if you can rebase it for 1.17.0 on this repo would be great. We're not yet at the point to switch the official add-on. 

I still need to "break the fork", prepare PR with docs update on z2m side.

**Comment by kind3r** [comment]
Ok, I think I managed to update the branch. Could you please check ?

**Pull request merged**
